/*
fn_KHC.sqf
Stirgoy
*/

private "_key";
_key = param [0,0,[0]];
_retStrKey = "";

switch (_key) do
{

	case 1: {_retStrKey = "ESC";};
	case 2: {_retStrKey = "1";};
	case 3: {_retStrKey = "2";};
	case 4: {_retStrKey = "3";};
	case 5: {_retStrKey = "4";};
	case 6: {_retStrKey = "5";};
	case 7: {_retStrKey = "6";};
	case 8: {_retStrKey = "7";};
	case 9: {_retStrKey = "8";};
	case 10: {_retStrKey = "9";};
	case 11: {_retStrKey = "0";};
	case 12: {_retStrKey = "'";};
	case 13: {_retStrKey = "¡";};
	case 14: {_retStrKey = "BKSP";};
	case 15: {_retStrKey = "TAB";};
	case 16: {_retStrKey = "Q";};
	case 17: {_retStrKey = "W";};
	case 18: {_retStrKey = "E";};
	case 19: {_retStrKey = "R";};
	case 20: {_retStrKey = "T";};
	case 21: {_retStrKey = "Y";};
	case 22: {_retStrKey = "U";};
	case 23: {_retStrKey = "I";};
	case 24: {_retStrKey = "O";};
	case 25: {_retStrKey = "P";};
	case 26: {_retStrKey = "`";};
	case 27: {_retStrKey = "+";};
	case 28: {_retStrKey = "ENTER";};
	case 29: {_retStrKey = "CTRL_R";};
	case 30: {_retStrKey = "A";};
	case 31: {_retStrKey = "S";};
	case 32: {_retStrKey = "D";};
	case 33: {_retStrKey = "F";};
	case 34: {_retStrKey = "G";};
	case 35: {_retStrKey = "H";};
	case 36: {_retStrKey = "J";};
	case 37: {_retStrKey = "K";};
	case 38: {_retStrKey = "L";};
	case 39: {_retStrKey = "Ñ";};
	case 40: {_retStrKey = "´";};
	case 41: {_retStrKey = "º";};
	case 42: {_retStrKey = "SHIFT_L";};
	case 43: {_retStrKey = "Ç";};
	case 44: {_retStrKey = "Z";};
	case 45: {_retStrKey = "X";};
	case 46: {_retStrKey = "C";};
	case 47: {_retStrKey = "V";};
	case 48: {_retStrKey = "B";};
	case 49: {_retStrKey = "N";};
	case 50: {_retStrKey = "M";};
	case 51: {_retStrKey = ",";};
	case 52: {_retStrKey = ".";};
	case 53: {_retStrKey = "-";};
	case 54: {_retStrKey = "SHIFT_R";};
	case 55: {_retStrKey = "N_*";};
	case 56: {_retStrKey = "ALT_R";};
	case 57: {_retStrKey = "SPACE";};
	case 58: {_retStrKey = "MAYUS";};
	case 59: {_retStrKey = "F1";};
	case 60: {_retStrKey = "F2";};
	case 61: {_retStrKey = "F3";};
	case 62: {_retStrKey = "F4";};
	case 63: {_retStrKey = "F5";};
	case 64: {_retStrKey = "F6";};
	case 65: {_retStrKey = "F7";};
	case 66: {_retStrKey = "F8";};
	case 67: {_retStrKey = "F9";};
	case 68: {_retStrKey = "F10";};
	case 69: {_retStrKey = "NUM";};
	case 70: {_retStrKey = "SROLL";};
	case 71: {_retStrKey = "N_7";};
	case 72: {_retStrKey = "N_8";};
	case 73: {_retStrKey = "N_9";};
	case 74: {_retStrKey = "N_-";};
	case 75: {_retStrKey = "N_4";};
	case 76: {_retStrKey = "N_5";};
	case 77: {_retStrKey = "N_6";};
	case 78: {_retStrKey = "N_+";};
	case 79: {_retStrKey = "N_1";};
	case 80: {_retStrKey = "N_2";};
	case 81: {_retStrKey = "N_3";};
	case 82: {_retStrKey = "N_0";};
	case 83: {_retStrKey = "N_.";};
	case 86: {_retStrKey = "<";};
	case 87: {_retStrKey = "F11";};
	case 88: {_retStrKey = "F12";};
	case 156: {_retStrKey = "N_ENTER";};
	case 157: {_retStrKey = "CTRL_L";};
	case 181: {_retStrKey = "N_/";};
	case 183: {_retStrKey = "PRINT";};
	case 184: {_retStrKey = "ALT_GR";};
	case 197: {_retStrKey = "PAUSE";};
	case 199: {_retStrKey = "INICIO";};
	case 200: {_retStrKey = "UP";};
	case 201: {_retStrKey = "REPAG";};
	case 203: {_retStrKey = "LEFT";};
	case 205: {_retStrKey = "RIGTH";};
	case 207: {_retStrKey = "END";};
	case 208: {_retStrKey = "DOWN";};
	case 209: {_retStrKey = "AVPAG";};
	case 210: {_retStrKey = "INSERT";};
	case 211: {_retStrKey = "DEL";};
	case 219: {_retStrKey = "WIN_R";};
	case 220: {_retStrKey = "WIN_L";};
	case 221: {_retStrKey = "APP";};
	default {_retStrKey = _key;};
};
_retStrKey
